# Generated by Django 6.0.4 on 2026-05-26 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_responsetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsetask',
            name='date_creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
