# Generated by Django 6.0.4 on 2026-05-11 07:11

import django.utils.timezone
import users.fields
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_myuser_groups_myuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=users.fields.PhoneField(blank=True, max_length=16, null=True, validators=[users.validators.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='myuser',
            name='status',
            field=models.CharField(choices=[('V', 'volunteer'), ('N', 'needy')], default='V', max_length=2),
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
