# Generated by Django 6.0.4 on 2026-05-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_myuser_city_myuser_description_myuser_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='status',
            field=models.CharField(choices=[('volunteer', 'волонтер'), ('needy', 'нуждающийся')], default='volunteer', max_length=10),
        ),
    ]
